In [1]:
import numpy as np
A = np.matrix([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [2]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
m = A.mean(axis=0)
print(m)
type(m)

[[5.5 6.5 7.5]]


numpy.matrix

In [6]:
A - A.mean(axis=0)

matrix([[-4.5, -4.5, -4.5],
        [-1.5, -1.5, -1.5],
        [ 1.5,  1.5,  1.5],
        [ 4.5,  4.5,  4.5]])